from pathlib import Path
p = Path(r'D:\Projects\bazi-portal\bazi-analysis.html')
s = p.read_text(encoding='utf-8', errors='ignore')

a1 = 'function elementBoxes(r){ return `<div class="element-grid"><div class="element-box"><div class="element-label">��</div><div class="element-num element-jin">${r.jin}</div></div><div class="element-box"><div class="element-label">ľ</div><div class="element-num element-mu">${r.mu}</div></div><div class="element-box"><div class="element-label">ˮ</div><div class="element-num element-shui">${r.shui}</div></div><div class="element-box"><div class="element-label">��</div><div class="element-num element-huo">${r.huo}</div></div><div class="element-box"><div class="element-label">��</div><div class="element-num element-tu">${r.tu}</div></div></div>`; } function renderRows(list){'
ins = 'function wxClass(wx){ return {\'金\':\'wx-jin\',\'木\':\'wx-mu\',\'水\':\'wx-shui\',\'火\':\'wx-huo\',\'土\':\'wx-tu\'}[wx] || \"\"; } function wxOfChar(ch){ return (ganMeta[ch]||zhiMeta[ch]||[\'未知\',\'\'])[0]; } function wxSpan(ch){ const wx = wxOfChar(ch); return `<span class="${wxClass(wx)}">${ch}</span>`; } function baziHtml(text){ return text.split(\' \' ).map(p=>`<span class="bazi-piece">${wxSpan(p[0])}${wxSpan(p[1])}</span>`).join(\"\"); } function pillarHtml(label,pillar){ const gan=pillar[0], zhi=pillar[1], g=ganMeta[gan], z=zhiMeta[zhi], c=(hiddenMap[zhi]||[]).map(wxSpan).join(\'、\'); return `<div class="pillar"><h3>${label}：${wxSpan(gan)}${wxSpan(zhi)}</h3><div class="meta-line"><span class="label-mini">天干</span>${wxSpan(gan)}（${g[1]}${g[0]}）</div><div class="meta-line"><span class="label-mini">地支</span>${wxSpan(zhi)}（${z[1]}${z[0]}）</div><div class="meta-line"><span class="label-mini">藏干</span><span class="canggan">${c}</span></div></div>`; } function hiddenSection(r){ return `<div class="section-bar">藏干展开：</div><div class="hidden-grid">${pillarHtml(\'年柱\',r.year)}${pillarHtml(\'月柱\',r.month)}${pillarHtml(\'日柱\',r.day)}${pillarHtml(\'时柱\',r.hour)}</div>`; } ' + a1
if a1 not in s: raise SystemExit('anchor1 not found')
s = s.replace(a1, ins, 1)

old2 = '<div class="note"><b>���֣�</b>${r.bazi}</div>${elementBoxes(r)}<div class="bottom-actions"><button class="btn" onclick="openModal(\'${r.pattern}\')">�Ƽ�����</button><a class="btn" href="names.html#${encodeURIComponent(r.pattern)}">������ҳ</a></div></article>`).join(\'\'); applyView(); }'
new2 = '<div class="bazi-line"><b>八字：</b>${baziHtml(r.bazi)}</div>${elementBoxes(r)}${hiddenSection(r)}<div class="bottom-actions"><button class="btn" onclick="openModal(\'${r.pattern}\')">�Ƽ�����</button><a class="btn" href="names.html#${encodeURIComponent(r.pattern)}">������ҳ</a></div></article>`).join(\'\'); applyView(); }'
if old2 not in s: raise SystemExit('anchor2 not found')
s = s.replace(old2, new2, 1)

css_old = '.element-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:16px}.element-box{padding:10px 6px;border-radius:16px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.07);text-align:center}.element-label{font-size:12px;color:var(--muted);margin-bottom:4px}.element-num{font-size:24px;font-weight:700}.element-jin{color:var(--gold)}.element-mu{color:var(--wood)}.element-shui{color:var(--water)}.element-huo{color:var(--fire)}.element-tu{color:var(--earth)}.bottom-actions{display:flex;justify-content:space-between;gap:12px;margin-top:16px}'
css_new = '.element-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:16px}.element-box{padding:10px 6px;border-radius:16px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.07);text-align:center}.element-label{font-size:12px;color:var(--muted);margin-bottom:4px}.element-num{font-size:24px;font-weight:700}.element-jin{color:var(--gold)}.element-mu{color:var(--wood)}.element-shui{color:var(--water)}.element-huo{color:var(--fire)}.element-tu{color:var(--earth)}.bazi-line{margin-top:14px;text-align:center;font-size:22px;font-weight:900;letter-spacing:.8px;line-height:1.4}.bazi-piece{display:inline-block;margin:0 4px}.section-bar{margin-top:14px;text-align:center;font-size:17px;font-weight:900;letter-spacing:.4px}.hidden-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}.pillar{padding:12px 12px 10px;border-radius:18px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08)}.pillar h3{margin:0 0 8px;font-size:15px;line-height:1.2;text-align:center;font-weight:900}.meta-line{margin:3px 0;font-size:12px;line-height:1.55;color:#eaf0ff;font-weight:700}.wx-jin{color:#f4cf7b}.wx-mu{color:#8bd5a0}.wx-shui{color:#8ab9ff}.wx-huo{color:#ff9db3}.wx-tu{color:#dcb58e}.canggan{font-weight:900;letter-spacing:.5px}.label-mini{display:inline-block;color:var(--muted);min-width:34px}.bottom-actions{display:flex;justify-content:space-between;gap:12px;margin-top:16px}'
if css_old in s: s = s.replace(css_old, css_new, 1)

mobile_old = '@media (max-width:1100px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pattern-grid{grid-template-columns:1fr}.toolbar{grid-template-columns:1fr 1fr}.name-grid{grid-template-columns:1fr}.wrap{padding:14px}.hero h1{font-size:24px}}\n@media (max-width:720px){.wrap{padding:10px}.hero{padding:18px;border-radius:20px}.hero h1{font-size:22px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.toolbar{grid-template-columns:1fr}.table-wrap{display:none}.cards{display:grid}.v{font-size:22px}.bazi-sticky{border-radius:24px;padding-left:18px;padding-right:18px;margin-left:0;margin-right:0;width:auto}.bazi-sticky.compact{border-radius:0;margin-left:calc(50% - 50vw);margin-right:calc(50% - 50vw);width:100vw;padding-left:max(8px, env(safe-area-inset-left));padding-right:max(8px, env(safe-area-inset-right))}.bazi-sticky::before{border-radius:24px}.bazi-sticky.compact::before{border-radius:0}.bazi-sticky .nav{justify-content:center}}'
mobile_new = '@media (max-width:1100px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pattern-grid{grid-template-columns:1fr}.toolbar{grid-template-columns:1fr 1fr}.name-grid{grid-template-columns:1fr}.wrap{padding:14px}.hero h1{font-size:24px}.hidden-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}\n@media (max-width:720px){.wrap{padding:10px}.hero{padding:18px;border-radius:20px}.hero h1{font-size:22px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.toolbar{grid-template-columns:1fr}.table-wrap{display:none}.cards{display:grid}.v{font-size:22px}.bazi-sticky{border-radius:24px;padding-left:18px;padding-right:18px;margin-left:0;margin-right:0;width:auto}.bazi-sticky.compact{border-radius:0;margin-left:calc(50% - 50vw);margin-right:calc(50% - 50vw);width:100vw;padding-left:max(8px, env(safe-area-inset-left));padding-right:max(8px, env(safe-area-inset-right))}.bazi-sticky::before{border-radius:24px}.bazi-sticky.compact::before{border-radius:0}.bazi-sticky .nav{justify-content:center}.bazi-line{font-size:18px}.section-bar{font-size:16px}.hidden-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.pillar{padding:10px}.pillar h3{font-size:14px}.meta-line{font-size:11px}}'
if mobile_old in s: s = s.replace(mobile_old, mobile_new, 1)

p.write_text(s, encoding='utf-8')
print('patched bazi-analysis enhanced blocks')
