from pathlib import Path

# names.html: replace dynamic incremental loading with stable full render + persistent detail state
path = Path(r'D:\Projects\bazi-portal\names.html')
text = path.read_text(encoding='utf-8')
start = text.find("let currentGender=")
end = text.rfind('</script></body></html>')
if start == -1 or end == -1 or end <= start:
    raise SystemExit('names tail boundary not found')

new_tail = r'''const patterns=["火格","土格","木火格","水火格","火土格","金火格"]; const container=document.getElementById('patterns'); const maleBtn=document.getElementById('maleBtn'); const femaleBtn=document.getElementById('femaleBtn'); const body=document.body; const topbar=document.getElementById('namesTopbar'); const genderScrollMemory={男:null,女:null}; const detailState={男:{},女:{}}; let suppressScrollMemoryWrite=false; let activePattern=''; let namesSwitching=false;
function isMobile(){ return window.innerWidth<=720; }
function detailKey(pattern,name){ return `${pattern}__${name}`; }
function isDetailOpen(pattern,name){ return !!detailState[currentGender][detailKey(pattern,name)]; }
function setDetailOpen(pattern,name,open){ detailState[currentGender][detailKey(pattern,name)] = !!open; }
function entryHtml(r,p){ const mobile=isMobile(); const open = mobile ? isDetailOpen(p, r.name) : true; return `<div class="name-line" data-name="${r.name}"><div class="subline"><div><div class="name-calligraphy" style="${patternStyle[p]}">${r.name}</div><span class="small">${r.pinyin}</span></div><div style="display:flex;flex-direction:column;align-items:flex-end;gap:8px"><div class="score">${r.score} 分</div>${mobile?`<button class="btn detail-toggle" type="button" data-detail-toggle="1" data-pattern="${p}" data-name="${r.name}">${open?'收起详情':'展开详情'}</button>`:''}</div></div><div class="note" ${mobile?`data-detail-body="1" style="display:${open?'block':'none'}"`:''}><b>五行：</b>${r.wuxing}<br><b class="meaning">组合意思：</b><span class="meaning">${r.meaning}</span><br><b>出处：</b>${r.source}<br><span class="reason"><b>评分理由：</b><strong>评分 ${r.score}</strong>：${r.reason.replace(/^评分\s*\d+[.:分]?/,'')}</span></div></div>`; }
function cardHtml(p){ const list=(currentGender==='男'?topData[p].boys:topData[p].girls); return `<article class="card pattern-card ${activePattern===p?'active-target':''}" id="${encodeURIComponent(p)}" data-pattern="${p}" style="background-image:${patternBg[p]}"><div class="pattern-headline"><div class="pattern-meta-left"><span class="badge">${patternDirection[p]}</span></div><div class="pattern-title-big" style="${patternStyle[p]}">${p}</div><div class="pattern-meta-right"><span class="badge">${list.length} 个名字</span></div></div>${list.map(r=>entryHtml(r,p)).join('')}</article>`; }
function lockGenderButtons(locked){ maleBtn.disabled=locked; femaleBtn.disabled=locked; maleBtn.style.pointerEvents=locked?'none':''; femaleBtn.style.pointerEvents=locked?'none':''; maleBtn.style.opacity=locked?'.72':''; femaleBtn.style.opacity=locked?'.72':''; }
function bindDetailToggles(){ container.querySelectorAll('[data-detail-toggle]').forEach(btn=>btn.onclick=()=>{ const pattern=btn.getAttribute('data-pattern'); const name=btn.getAttribute('data-name'); const item=btn.closest('.name-line'); const detail=item&&item.querySelector('[data-detail-body]'); if(!detail) return; const open = detail.style.display !== 'none'; const next = !open; detail.style.display = next ? 'block' : 'none'; btn.textContent = next ? '收起详情' : '展开详情'; setDetailOpen(pattern, name, next); }); }
function updateTopbar(){ const y=window.scrollY||window.pageYOffset||0; topbar.classList.toggle('sticky', y>10); topbar.classList.toggle('compact', y>32); if(!suppressScrollMemoryWrite) genderScrollMemory[currentGender]=y; }
function getPatternFromHash(){ const raw=decodeURIComponent((location.hash||'').replace(/^#/,'')); return patterns.find(p=>p===raw)||''; }
function jumpToPattern(pattern,behavior='smooth'){ if(!pattern) return; activePattern=pattern; const node=container.querySelector(`[data-pattern="${pattern}"]`); if(!node) return; container.querySelectorAll('.pattern-card.active-target').forEach(el=>el.classList.remove('active-target')); node.classList.add('active-target'); node.scrollIntoView({block:'start',behavior}); }
function syncHashTarget(behavior='auto'){ const pattern=getPatternFromHash(); if(!pattern) return; activePattern=pattern; requestAnimationFrame(()=>jumpToPattern(pattern,behavior)); }
function render(resetScroll=false){ container.innerHTML = patterns.map(p=>cardHtml(p)).join(''); bindDetailToggles(); updateTopbar(); if(resetScroll){ suppressScrollMemoryWrite=true; window.scrollTo({top:0,behavior:'auto'}); requestAnimationFrame(()=>{ suppressScrollMemoryWrite=false; updateTopbar(); }); } syncHashTarget('auto'); }
function switchGender(nextGender){ if(nextGender===currentGender || namesSwitching) return; namesSwitching=true; lockGenderButtons(true); const prevGender=currentGender; genderScrollMemory[prevGender]=window.scrollY||window.pageYOffset||0; currentGender=nextGender; body.className=nextGender==='男'?'names-page theme-male':'names-page theme-female'; maleBtn.classList.toggle('active', nextGender==='男'); femaleBtn.classList.toggle('active', nextGender==='女'); suppressScrollMemoryWrite=true; render(false); requestAnimationFrame(()=>{ const target=getPatternFromHash(); if(target){ jumpToPattern(target,'auto'); } else { const targetY=genderScrollMemory[nextGender]==null?0:genderScrollMemory[nextGender]; window.scrollTo({top:targetY,behavior:'auto'}); } requestAnimationFrame(()=>{ suppressScrollMemoryWrite=false; updateTopbar(); namesSwitching=false; lockGenderButtons(false); }); }); }
let currentGender='男'; body.className='names-page theme-male'; maleBtn.classList.add('active'); femaleBtn.classList.remove('active'); maleBtn.onclick=()=>switchGender('男'); femaleBtn.onclick=()=>switchGender('女'); window.addEventListener('scroll', updateTopbar,{passive:true}); window.addEventListener('hashchange', ()=>syncHashTarget('smooth')); window.addEventListener('resize', ()=>{ genderScrollMemory[currentGender]=window.scrollY||window.pageYOffset||0; suppressScrollMemoryWrite=true; render(false); requestAnimationFrame(()=>window.scrollTo({top:genderScrollMemory[currentGender]||0,behavior:'auto'})); requestAnimationFrame(()=>{ suppressScrollMemoryWrite=false; updateTopbar(); syncHashTarget('auto'); }); }); window.__namesDebug={get patterns(){return patterns;},get currentGender(){return currentGender;},get detailState(){return detailState;}}; render();'''

text = text[:start] + new_tail + text[end:]
path.write_text(text, encoding='utf-8')
print('rewrote names runtime')
